# Generated by Django 2.2.13 on 2020-07-24 18:42

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('sence', '0002_eolsencestudentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolsencestudentstatus',
            name='course',
            field=opaque_keys.edx.django.models.CourseKeyField(max_length=50),
        ),
    ]
