# Generated by Django 2.2.13 on 2020-07-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sence', '0003_auto_20200724_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eolsencecoursesetup',
            old_name='sense_code',
            new_name='sence_code',
        ),
        migrations.RenameField(
            model_name='eolsencecoursesetup',
            old_name='sense_line',
            new_name='sence_line',
        ),
    ]
