# Generated by Django 2.2.13 on 2020-07-28 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sence', '0005_eolsencecoursesetup_sence_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eolsencecoursesetup',
            name='sence_course_code',
        ),
        migrations.AlterField(
            model_name='eolsencestudentstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sence_user_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EolSenceStudentSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', opaque_keys.edx.django.models.CourseKeyField(max_length=50)),
                ('sence_course_code', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sence_user_setup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
                'index_together': {('user', 'course')},
            },
        ),
    ]
