# Generated by Django 2.2.13 on 2020-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sence', '0006_auto_20200728_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolsencestudentsetup',
            name='user_run',
            field=models.CharField(default=123456789, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='eolsencestudentsetup',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='eolsencestudentsetup',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='eolsencestudentsetup',
            name='user',
        ),
    ]
