name: Python application

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - 'koa'
      - 'lilac'
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'koa'
      - 'lilac'
      - 'master'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    uses: eol-uchile/workflow-commons/.github/workflows/pythonapp.yml@1.0.0
    with:
      app_id: ${{ vars.EOLITO_BOT_APP_ID }}
      django-lms: true
      django-cms: false
      platform-eol: true
      platform-openuchile: true
    secrets:
      private_key: ${{ secrets.EOLITO_BOT_PRIVATE_KEY }}
