name: Python application

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'koa'
      - 'lilac'
      - 'master'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    uses: eol-uchile/eol_feedback/.github/workflows/pythonapp.yml@master
